# Catppuccin Mocha + Orange accent
set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"

set -g window-status-current-style fg="#1e1e2e",bg="#ee960e"
set -g window-status-style fg="#585b70",bg="#1e1e2e"
set -g window-status-separator ""

set -g pane-active-border-style fg="#ee960e"
set -g pane-border-style fg="#45475a"

set -g message-style fg="#1e1e2e",bg="#ee960e"
set -g message-command-style fg="#1e1e2e",bg="#ee960e"

set -g display-panes-active-colour "#ee960e"
set -g display-panes-colour "#45475a"

set -g status-left "#[fg=#ee960e]#S "
set -g status-right "#[fg=#585b70]%Y-%m-%d %I:%M"
